### ISSUE TITLE
Enabling the extension makes new windows appear behind de current app

### ISSUE THREAD

**Issue by fredszaq** [diegodario88/quake-terminal#11]
Hi there ! 

Thanks for this awesome extension for gnome 45 ! 

I however have a small annoying problem when enabling it: when quake terminal is enabled, new apps are launched behind the current app (instead of in front)

Here is a video showing the problem (I first show the expected behavior, then enable quake terminal, test it works an try relaunching a new app)

[Screencast from 2023-10-19 10-24-46.webm](https://github.com/diegodario88/quake-terminal/assets/1485368/e4e9037c-0056-4d73-9520-f8f533438d11)

The terminal at the end appears behind the files app, it should be above. disabling quake terminal restores the expected behavior

I'm using Tilix as the app handled by quake terminal in the video, the same problem happens with the default gnome terminal.

This is especially annoying when the current app is taking the full screen. 

Technical details : 
 - archlinux, with `gnome-shell` version `1:45.0+r17+gebf2f8036-1`
 - windowing system : wayland
 - graphics cards : intel uhd 630 (primary) + nvidia quadro T2000 mobile (using nouveau, not in use when single screening)
 - quake terminal version 11 (from extensions.gnome.org)

Let me know how I can help to fix this

**Comment by diegodario88** [comment]
Hey there!

I checked out the video you provided, and I understand the issue you're encountering. It seems that when you enable the Quake terminal, new apps windows are launching behind the current ones without focus, which is indeed not the expected behavior.

However, I tried to reproduce the issue on my setup, but I wasn't able to encounter the same problem.  😔

In here, every new app window is opened with focus and above any other in the current workspace regardless quake-terminal extension is enabled or not.

Could you please try if enabling `auto hide` option in the extension preferences  change anything for you?

**Comment by fredszaq** [comment]
Enabling or disabling auto hide doesn't change the behavior (I had it enabled previously)

**Comment by diegodario88** [comment]
Hi there, @fredszaq! 

Could you do us a favor and give the version on the main branch a try to see if it resolves your issue?

Your feedback would be much appreciated! Thanks!

**Comment by fredszaq** [comment]
Hey @diegodario88 ! the last main fixes the problem ! thanks a lot !

**Comment by diegodario88** [comment]
I'm glad I could help you. If you find our open-source project valuable, please consider showing your support by donating or leaving a star on our repository. It means a lot to me.
