### ISSUE TITLE
Position on primary monitor

### ISSUE THREAD

**Issue by Henry78** [diegodario88/quake-terminal#15]
!5 was implemented and now I'm able to choose which monitor to put the terminal on. But when the configured monitor is detached an reattached, quake-terminal does not switch back to it. I'd like to see the terminal popping up at my external display when it's attached, otherwise the internal display (i.e. the active display at a time).

Pleas allow quake-terminal to be configured to the active monitor, as this is alredy handled by Gnome and should work fine.

**Comment by diegodario88** [comment]
Hey @Henry78, could you please share more about your workflow? Since I don't have another display to test it out, I'll need to ask you a few questions.

You're using two monitors, with one being the secondary display where the Quake terminal configuration is located. If you unplug the secondary monitor and the Quake terminal is now displayed on your main monitor, does it still show on the main screen when you plug the external monitor back in?

How frequently does this issue occur?

> It would be great if Quake-terminal could be configured to the active monitor, especially since this functionality is already  Mhandled by Gnome and should work seamlessly.

Could you provide more details on this, please? Specifically, what do you mean by "allow it to be configured to the active monitor..."?

**Comment by Henry78** [comment]
> How frequently does this issue occur?

Basically every time I detach my external (primary) display and the internal laptop screen becomes the only/last one. In this (detached) state, the configuration of quake-terminal is changed (unclear why/how), so the ID of the internal display shows up at "Monitor Screen" option. As a result the Terminal keeps opening on the internal screen after re-attaching the external display.

> Could you provide more details on this, please? Specifically, what do you mean by "allow it to be configured to the active monitor..."?

Sorry, 'primary display' is term used by Gnome. You can setup any connected display as Primary  (where the panel is shown). If the display is unplugged and reconnected, Gnome remembers that this was the primary.

There's another extension, I think it was ddterm, that has to option to configure the Primary Display over any specific one in the settings. That means, quake-terminal would have and additional `Primary` option at the "Monitor Screen" setting. This should make the Terminal to pop up at the screen that's the Primary at any moment.

**Comment by petre2dor** [comment]
I am interested in contributing to this improvement as I would like to use this functionality myself.
As a timid first step, I opened a **PR (#19)** to improve the Monitor Screen field in Preferences.

**Comment by petre2dor** [comment]
My general plan would be to:

1. change the default behavior so that the Quake Terminal opens on the Primary Display when it does not have any saved settings for the current Display configuration
2. whenever the user changes the preferred Display, then save that configuration and apply it whenever the same display configuration is encountered 
3. align the language of this extension with the language used by Gnome Display Settings screen

@diegodario88 does this plan sound decent to you? If implemented you your standards, you would be willing to accept these changes? I will try to create PRs with the smallest possible changes. 

Cheers!

**Comment by diegodario88** [comment]
Hey @petre2dor,

Thanks for sharing your plan for the extension. I'm on board with your proposed changes, and I appreciate your intention to keep the PRs as minimal as possible. This way, we can ensure a smoother integration.

Cheers, and thanks for your dedication to improving the extension! 🚀👍

**Comment by petre2dor** [comment]
@Henry78 I added "Show on the primary Display" and "Show on the current Display" options in this PR: https://github.com/diegodario88/quake-terminal/pull/20
If you have the time, please test my changes and give me some feedback.

Cheers!

**Comment by Henry78** [comment]
Tested with Laptop & external monitor. Both settings, 'Primary' and 'Current' worked very well. Tests included plugging in and out the external monitor a few times.

No issues.
