### ISSUE TITLE
Allow args to be passed to the selected terminal

### ISSUE THREAD

**Issue by pombadev** [diegodario88/quake-terminal#30]
Hi @diegodario88, thanks for the awesome piece of software, it's the only thing that works on gnome wayland without any issue.

I want to be able to pass args to the current terminal, to specify which profiles or behavior.

Eg: `flatpak run org.wezfurlong.wezterm --config='tab_bar_at_bottom=true' --config='pane_focus_follows_mouse=true'` 

Thank you!

**Comment by diegodario88** [comment]
I've been contemplating this proposal, and one straightforward method for its implementation involves adding a new action in the `.desktop` file. Instead of merely requesting the opening of a new window for the terminal application, we would initiate a custom action that users can register along with custom arguments.

For instance:

```bash
[Desktop Action QuakeTerminal]
Name=QuakeTerminal
Exec=flatpak run org.wezfurlong.wezterm --config='tab_bar_at_bottom=true' --config='pane_focus_follows_mouse=true'
``` 

then instead of `this._terminal.open_new_window(-1);` 
we would `this._terminal.launch_action('QuakeTerminal',  0, -1)`

To enable this functionality, we need to:
- [ ] add a new gschema key to store user action
- [ ] in the `prefs.js`, provide a way for users to assign their action name
- [ ] validate if the action name is valid. Maybe calling `this._terminal.get_app_info().list_actions()`
- [ ] refac `_launchTerminalWindow()` method

**Comment by diegodario88** [comment]
feel free to reopen
