### ISSUE TITLE
Choose side of emergence, aligment, widht and height

### ISSUE THREAD

**Issue by Henry78** [diegodario88/quake-terminal#7]
**Feature request**

Let the user choose the edge of the screen the drop down emerges from. Also make it's alignment, width and length configurable. Currently only the height can be configured.

Examples
  - (already implemented) drop down from top and use 50% of the screen height (100% width)
  - (improvement) drop down from top, centered, and use 50% of the screen height and 80% of it's width
  - (improvement) appear from the right edge, align top and use 50% of the screen height and 60% of it's width

**Comment by diegodario88** [comment]
@Henry78, Thank you for your support, feedback, and feature requests. I'm working on an implementation that adds the ability for users to choose the width and height more precisely. Additionally, I'll make **alignment**, **width**, and **length** configurable to provide more flexibility and customization.

However, I understand your point about launching the quake terminal from a place other than the top being a widely expected behavior. To maintain consistency and meet general user expectations, we'll keep the default behavior of launching the terminal from the top of the screen, at least for now.
